.github/workflows/main.yml

This job is intended to run at 00:00 and 12:00 UTC everyday. But it was
scheduled to run on the 0th day of the 0th months at those times
instead. Replacing the zeros with asterisks corrects the schedule.

Fix schedule syntax

---

mirror-plugins

Whilst using `git ls-remote` works locally for checking if a repo exists, it 
is failing in the context of GitHub actions, and always returning an error. 
This means the script always thinks the repo doesn't already exist, and 
then tries (and fails) to create it again.
I'm not entirely sure why this is, but I think it may be because we're
already inside a git repo (this one, checked out by the checkout
action), and that's causing a conflict.
So instead, let's call the API. If we get a 200 response, the repo
we're looking for exists, if we get anything else, it doesn't.
Because we just want the response code, we're using CURL to call the API
here, rather than `gh api`.

Use GitHub API call to confirm if repo exists

---

.github/workflows/main.yml

Now this task is running reliably, it is typically only taking 10-15
mins per run. Therefore, let's run it much more frequently to ensure
everything is up to date.
This is a public repo, so we won't burn through any GitHub minutes
allocation by doing this.

Run sync every hour

---

.github/workflows/main.yml

GitHub automatically disables scheduled workflows on public repos that
have had no activity for 60 days. It currently defines "activity" as git
activity on the default branch.
This causes an issue in this repo, as we need the task to mirror the
plugins to run indefinitely.
This commit adds dxw's fork of the keepalive-workflow action to address
this problem. This action adds an empty commit to the default branch
every 50 days, if there has been no other activity in the meantime. It's
not an ideal way of solving the problem, but it's better than the
workflow repeatedly deactivating, which is the only other option at the
moment.
We've implemented this approach successfully on other dxw repos, e.g.
https://github.com/dxw/golden-retriever/pull/126

Use keep-workflow-alive to ensure scheduled workflow stays active

---

.github/workflows/main.yml

The previous version we were using (1.06) didn't push the commit it
generated to the repo, so therefore didn't generate the necessary
activity to stop the repo being marked as inactive. This latest version
fixes that issue (see
https://github.com/gautamkrishnar/keepalive-workflow/pull/3).
I've also switched to using the upstream version, rather than our fork.
If we pin to a specific commit we're happy with (as I've done here),
this is equally safe.

Use v1.0.7 of keepalive-workflow

---

.env.example
README.md
mirror-plugins

This adds the ability to run the command in dry-run mode by setting an env var of `DRY_RUN=true`.
Note that I've used a different way of accessing the env var here - `ENV['var_name']` rather than `ENV.fetch('var_name')` as the latter will error if the variable doesn't exist, whereas the former will just return a default value of false.
1. Copy the `env.example` file to `.env` and populate as follows:
```
GITLAB_API_ENDPOINT=https://git.govpress.com/api/v4
GITLAB_WORDPRESS_PLUGINS_GROUP_ID=71
GH_ORG_NAME=dxw-wordpress-plugins
DEFAULT_BRANCH_NAME=master
GH_TEAM_ID=1234567 #this value will not be used so a random integer will do
GH_ACCOUNT_USERNAME=dxw-govpress-tools
GH_ACCOUNT_TOKEN=[the "mirror-gitlab-plugins" API token from the 1password entry for the github govpress tools service …
```

Add a dry run mode

---

.github/workflows/wordpress-mirror.yml
mirror-wordpress-plugins

This PR adds three small maintenance changes to the wordpress.org version of the mirror script which is currently running in `dry-run` mode.
To avoid a deprecation warning about Node.
Previously we just listed the plugins that had been updated. Now we also state which version they were updated to. For example:
-------------------------------------------------------------
==> Updated the following 1 plugin(s):
category-specific-rss-feed-menu was updated to version v2.3.1
We are consistently seeing errors of this form in the logs:
fatal: could not read Username for 'https://github.com/': No such device or address
[This log is a good example](https://github.com/dxw-wordpress-plugins/mirror-gitlab-plugins/actions/runs/9123771834/job/25086767304).
Which indicates that logging in with `gh` has …

Wordpress mirror maintenance

---

.github/workflows/wordpress-mirror.yml

In the scheduled job we are seeing errors of the form:
Author identity unknown
This doesn't appear in local dev envs, presumably
because developers all have Git fully configured.
This error also does not appear on the GitLab
scheduled jobs, possibly because we clone with
`--mirror` which sets up repositories slightly
differently to a normal clone operation.
This commit adds the small amount of configuration that should be needed to commit, tag and push
from the mirrors.

Add global Git configuration to workflow

---

.env.wordpress-example
.github/workflows/wordpress-mirror.yml
mirror-wordpress-plugins

This PR changes the way we deal with failures from the wordpress.org API. Previously, we raised an exception and carried on. Now, we "annotate" the plugin by adding repository topics that explain why the plugin is not available on wordpress.org and the `skip-mirror` topic, so that we don't try to update from WordPress again.
Repo topics are of the form:
* `status:<string>` for error messages, e.g. `status:closed` or `status:plugin-not-found`
* `reason:<string>` for the `reason` key in JSON, e.g. `reason:security-issue`, `reason:merged-into-core`, etc.
The intention here is that prefixes are unique, i.e. each repository should have only one `status` or `reason` topic set, and any old topics of the same "type" are removed before adding a new one.
Later on, this convention will help us add …

Add topics to repos with api failures

---

mirror-wordpress-plugins

Unlike in GitLab, where ':' and '::' are commonly
used as label separators, GitHub only allows characters in the range [A-Za-z0-9\-] in topics.
This commit changes the colon separator to a hyphen. It does not change the 'skip-mirror' topic.
See:
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics
I don't think much is needed here. A dry-run of the script won't catch this error because the dry-run doesn't actually set a topic. If you want to see the error message, manually setting a topic for this repo will trigger it.

Topics are separated by a hyphen

---

mirror-wordpress-plugins

This is not a string in the data we get back from GitHub, it's an associative array, so we need to index the value we want to pass to the PluginUpdater instance.

FIX default branch name passed to PluginUpdater

---

mirror-wordpress-plugins

GitHub needs a URI with credentials to perform a push.

Push to correct GitHub URI

---

mirror-wordpress-plugins

'git push --tags' only pushes tags, not commits and in this case we also need to push tags with force, to overwrite major version tags (e.g. 'v1'). So, this commit separates the two calls to 'git push'.

Push code changes and tags separately

---

.github/workflows/tagger.yml

This workflow will run the major version tagger every 2 hours. This greater frequency than the mirroring should ensure we always catch any plugins that need tagging.
Currently the tagging script will always run in a dry-run state (even if `DRY_RUN_TAGGER` isn't set), so this will just allow us to keep an eye on it and check it runs consistently without errors.

Add scheduled workflow for major-version-tagger script

---

apply-major-version-tags
mirror-wordpress-plugins

This PR removes the major tagging logic from the mirroring script, and enables it fully in the tagging script. This will activate the tagging script, and enable us to auto-tag manually as well as automatically updated repos.

Switch to tagger script for major tags

---

.github/workflows/wordpress-mirror.yml

We've got a bug in the mirroring from WordPress. Until it's fixed, it'll be easier to not run the mirroring task.
I've left the workflow_dispatch option there, so we can manually trigger the workflow if we want to.

Disable scheduled mirror runs

---

README.md

The old docs referred to the previous mirror script, I think

FIX docs on how to limit deploys

---

mirror-wordpress-plugins

Previously the code to extract zip files from wordpress.org and copy them to the Git clone from GitHub was based on the PHP code from Whippet racetrack. There were some modifications to work around the way the rubyzip library worked, which meant that we unzipped the archive in a temporary folder and then moved the files over to the Git clone.
This code contained a bug which meant that sometimes the directory structure in the archive was not the same as the directory structure in the clone. Some repos had extra directories added which contained the top-level files and otherse seemed to have directories removed.
This commit fixes that by replacing the old way of committing to the clone with the manual process we use for pro-plugins. Here, we clone the plugin repo from the library, delete …

FIX incorrect file copying to Git clones

---

mirror-wordpress-plugins

Previously this check caught paths like '.gitkeep' which we do want to delete, so this commit makes the check more specific to '.git' directories.

More specific check for .git paths

---

.github/workflows/wordpress-mirror.yml

This reverts commit ba1a1e62bb47daa3c9a78bc7bd9b122d85e0aed7, which temporarily removed the scheduled task to mirror WordPress plugins from wordpress.org while we fixed it. That is now done, so it can be reinstated.

Revert "Disable scheduled mirror runs"

---

mirror-wordpress-plugins

Previously, we assumed that if 'gh' and 'jq' could not find any version information from a GitHub plugin repo then the shell command would exit with a non-zero exit code.
In practice, we have found (with the 'loco-translate' plugin) that the shell exec writes some text to stderr and exit with status 0. However, it returns the string '.\n'.
In this commit we check for that string that is returned by 'jq' and if that is the result of the shell exec we return an empty string, indicating that the repo had no tags.
This is important because when we mirror an entirely new plugin, we do so from a completely empty repository.
```shell
==> Fetching all GitHub plugin repositories in the library...
==> Found 786 plugins in the library
------------------------------------------------------------------ …
```

FIX version discovery for empty GitHub repos

---

mirror-wordpress-plugins

In Incident 201 we found that the Two-Factor plugin did not mirror correctly. We could not reproduce the error, but noted that had it been caused by a corrupted .zip file, we would not have caught the error. This commit corrects that by catching errors on unzipping archive files and adding the error to the failure list at the end of the log, e.g.:
==> Failed to update the following 1 plugin(s):
*** Two-Factor failed to update with message:
Zip end of central directory signature not found
This PR also adds a little more text to the logs and one more explicit `rescue` (which will be harder to test).
1. Follow the instructions in the README about dry-running the code. You may want to comment out lines 137-139 in this branch (to avoid deleting files). Do this once to get at least one .zip …

Be more defensive about extracting zipfiles

---

.env.example
mirror-wordpress-plugins

Fixes #51 
This PR:
* Changes the behaviour of `DRY_RUN_MIRROR` so that a dry run does not clean up downloaded files (the .zip file from WordPress and the cloned repository).
* Adds a `NO_CLONE_MIRROR` env var to switch of `git clone` (for local testing)
* Adds a `NO_DOWNLOAD_MIRROR` env var to switch off downloading .zip files (for local testing)
* Explicitly tests whether the link to the .zip from WordPress returns a 200 OK. If it does not, this is now caught by the `rescue` in the `extract_zip` method but that only tells us that the archive could not be extracted. If the archive link is a 404 (for example) `curl` will download an ASCII text notice which cannot be treated as a .zip file. So this change just gives us a better error message.
This PR does not:
* Refactor the code. This …

Make local testing easier

---

apply-major-version-tags
lib/error_mixin.rb
lib/plugin_verifier.rb
mirror-wordpress-plugins

Follow-up to INC-201: the mirror script validates files mirrored from wordpress.org.
You can see an example of the JSON data used to verify files here:
https://downloads.wordpress.org/plugin-checksums/woocommerce/8.6.0.json
* This PR contains a small amount of refactoring to ensure that we do not add too many new lines to the mirror script which is already long. It does _not_ attempt a full refactor, but that would be a good addition to a separate PR.
* This PR does not add to the GitHub workflows. This would need a new top-level script which ideally would include some more aggressive refactoring, so that's left to future PR.
1. Make sure your `.env` is set up to run both scripts as dry runs and to force all actions across the library.
2. Run the `apply-major-version-tags` script in …

Validate plugin checksums

---

mirror-wordpress-plugins

Previously if the user set NO_CLONE_MIRROR in their .env file we did not clone mirrored repos but we did try to perform other Git operations on those clones, such as add, commit and tag. This resulted in the
operations being applied to this repository which
is confusing behaviour and risks errant commits
being pushed to a feature branch.
This commit adds more defensive behaviour around
Git operations to check the environment variables
as appropriate.
Fixes https://github.com/dxw-wordpress-plugins/mirror-wordpress-plugins/issues/56
On this feature branch:
1. Add `NO_CLONE_MIRROR=true` to your `.env` file, make sure you are also running everything in dry run mode
2. Run the mirror script until at least one plugin that can be updated has finished executing
3. Check that you see the new lines …

NO_CLONE_MIRROR implies no use of a Git repo clone

---

lib/plugin_verifier.rb

To mitigate this error from this morning:
*** geo-my-wp failed to update with message:
.gitattributes checksum mismatch. File does not exist in GitHub repository.

Checksum validation ignores .gitattributes

---

lib/plugin_verifier.rb

*** geo-my-wp failed to update with message:
.gitignore checksum mismatch. File does not exist in GitHub repository.
and then validated in a local dry-run.

Checksum verifier ignores more files and directories

---

.github/workflows/tagger.yml
.github/workflows/wordpress-mirror.yml

Scheduled workflows in this repository tend to timeout, which means that we need a keepalive workflow to ensure that any operations that run over the whole plugin library run to completion.
The workflow we used before is this:
https://github.com/gautamkrishnar/keepalive-workflow
and currently has a notice on the repo page:
Access to this repository has been disabled by GitHub Staff
due to a violation of GitHub's terms of service. If you are
the owner of the repository, you may reach out to GitHub
Support for more information.
To ensure that the actions do not fail, this commit replaces that workflow with this one:
https://github.com/liskin/gh-workflow-keepalive/
Pinned to the commit we reviewed, which was:
f72ff1a1336129f29bf0166c0fd0ca6cf1bcb38c

Replace the keepalive workflow
